name: Display Secrets from File

on:
  workflow_dispatch:

jobs:


  Approval-Backend:
    if: |
      github.event.inputs.environment == 'dev' ||
      github.event.inputs.environment == 'uat' ||
      github.event.inputs.environment == 'preprod'
    runs-on: ubuntu-latest
    environment: approval-backend
    steps:
      - name: Approval
        run: echo 'Approved by backend!'  

  Approval-SRE:
    if: github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    environment: approval-sre
    steps:
      - name: Approval
        run: echo 'Approved by SRE!'       

  dev-secrets:
    runs-on: ubuntu-latest
    needs: Approval-Backend
    env:
      environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display secrets.txt contents (dev)
        run: |
          if [ -f secrets.txt ]; then
            echo "Contents of secrets.txt (dev):"
            cat secrets.txt
          else
            echo "secrets.txt not found"
          fi

  uat-secrets:
    runs-on: ubuntu-latest
    needs: [Approval-Backend, dev-secrets]
    env:
      environment: uat
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display secrets.txt contents (uat)
        run: |
          if [ -f secrets.txt ]; then
            echo "Contents of secrets.txt (uat):"
            cat secrets.txt
          else
            echo "secrets.txt not found"
          fi

  preprod-secrets:
    runs-on: ubuntu-latest
    needs: [Approval-Backend, uat-secrets]
    env:
      environment: preprod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display secrets.txt contents (preprod)
        run: |
          if [ -f secrets.txt ]; then
            echo "Contents of secrets.txt (preprod):"
            cat secrets.txt
          else
            echo "secrets.txt not found"
          fi

  prod-secrets:
    runs-on: ubuntu-latest
    needs: [Approval-SRE, preprod-secrets]
    env:
      environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display secrets.txt contents (prod)
        run: |
          if [ -f secrets.txt ]; then
            echo "Contents of secrets.txt (prod):"
            cat secrets.txt
          else
            echo "secrets.txt not found"
          fi
