name: Display Secrets from File

on:
  workflow_dispatch:

jobs:
  Approval-Backend-Dev:
    runs-on: ubuntu-latest
    environment: approval-backend
    steps:
      - name: Approval
        run: echo 'Approved by backend for dev!'

  dev-secrets:
    runs-on: ubuntu-latest
    needs: Approval-Backend-Dev
    environment: dev    
    env:
      # environment: dev
      AZURE_KEYVAULT: ${{ vars.AZURE_KEYVAULT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display secrets.txt contents (dev)
        run: |
          if [ -f secrets.txt ]; then
            echo "Azure Key Vault: $AZURE_KEYVAULT"
            echo "Environment: $environment"          
            echo "Contents of secrets.txt (dev):"
            cat secrets.txt
          else
            echo "secrets.txt not found"
          fi

  Approval-Backend-Uat:
    runs-on: ubuntu-latest
    needs: dev-secrets
    environment: approval-backend
    steps:
      - name: Approval
        run: echo 'Approved by backend for uat!'

  uat-secrets:
    runs-on: ubuntu-latest
    needs: [Approval-Backend-Uat, dev-secrets]
    environment: uat
    env:
      # environment: uat
      AZURE_KEYVAULT: ${{ vars.AZURE_KEYVAULT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display secrets.txt contents (uat)
        run: |
          if [ -f secrets.txt ]; then
            echo "Azure Key Vault: $AZURE_KEYVAULT"
            echo "Environment: $environment"          
            echo "Contents of secrets.txt (uat):"
            cat secrets.txt
          else
            echo "secrets.txt not found"
          fi

  Approval-Backend-Preprod:
    runs-on: ubuntu-latest
    needs: uat-secrets
    environment: approval-backend
    steps:
      - name: Approval
        run: echo 'Approved by backend for preprod!'

  preprod-secrets:
    runs-on: ubuntu-latest
    needs: [Approval-Backend-Preprod, uat-secrets]
    environment: preprod
    env:
      # environment: preprod
      AZURE_KEYVAULT: ${{ vars.AZURE_KEYVAULT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display secrets.txt contents (preprod)
        run: |
          if [ -f secrets.txt ]; then
            echo "Azure Key Vault: $AZURE_KEYVAULT"
            echo "Environment: $environment"          
            echo "Contents of secrets.txt (preprod):"
            cat secrets.txt
          else
            echo "secrets.txt not found"
          fi

  Approval-SRE:
    runs-on: ubuntu-latest
    needs: preprod-secrets
    environment: approval-sre
    steps:
      - name: Approval
        run: echo 'Approved by SRE!'

  prod-secrets:
    runs-on: ubuntu-latest
    needs: [Approval-SRE, preprod-secrets]
    environment: prod
    env:
      # environment: prod
      AZURE_KEYVAULT: ${{ vars.AZURE_KEYVAULT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display secrets.txt contents (prod)
        run: |
          if [ -f secrets.txt ]; then
            echo "Azure Key Vault: $AZURE_KEYVAULT"
            echo "Environment: $environment"
            echo "Contents of secrets.txt (prod):"
            cat secrets.txt
          else
            echo "secrets.txt not found"
          fi
